#! /bin/sh
#1: Full path of file to be compiled
#2: Directory
#3: Filename

fullPath="$1"

# dir="$2/"
# fileName="$3"

notify-send "fullPath: $fullPath dir: $dir filename: $filename"

# swpFile="$2.$3.swp"


# notify-send "Monitoring $swpFile"


# echo "$swpFile" | entr pandoc -f markdown $fullPath -o /tmp/compileMd.pdf 
#  nohup zathura /tmp/compileMd.pdf 2> /dev/null > /dev/null &
