#!/bin/bash
# Check to see if htop is running, and show if it is

if ! pgrep -f 'octave' ; then
    i3-msg "exec --no-startup-id gnome-terminal -title "dropdown" -e "octave --no-gui""
    sleep 1
fi
i3-msg "[title=\"dropdown\"] scratchpad show"

